/*
 * This file is generated by jOOQ.
 */
package lee.minjae.testjooq.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import lee.minjae.testjooq.jooq.tables.Dictionary;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictionaryRecord extends UpdatableRecordImpl<DictionaryRecord> implements Record12<Integer, String, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -71716815;

    /**
     * Setter for <code>test.dictionary.test_id</code>.
     */
    public DictionaryRecord setTestId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.test_id</code>.
     */
    public Integer getTestId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.dictionary.korean_word</code>. 한국어 단어
     */
    public DictionaryRecord setKoreanWord(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.korean_word</code>. 한국어 단어
     */
    public String getKoreanWord() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.dictionary.english_full_word</code>. 영문 단어
     */
    public DictionaryRecord setEnglishFullWord(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.english_full_word</code>. 영문 단어
     */
    public String getEnglishFullWord() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.dictionary.english_short_word</code>. 영문 축약어
     */
    public DictionaryRecord setEnglishShortWord(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.english_short_word</code>. 영문 축약어
     */
    public String getEnglishShortWord() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.dictionary.use_yn</code>. 사용 여부
     */
    public DictionaryRecord setUseYn(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.use_yn</code>. 사용 여부
     */
    public Boolean getUseYn() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>test.dictionary.package_yn</code>.
     */
    public DictionaryRecord setPackageYn(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.package_yn</code>.
     */
    public Boolean getPackageYn() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>test.dictionary.class_yn</code>.
     */
    public DictionaryRecord setClassYn(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.class_yn</code>.
     */
    public Boolean getClassYn() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>test.dictionary.variable_yn</code>.
     */
    public DictionaryRecord setVariableYn(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.variable_yn</code>.
     */
    public Boolean getVariableYn() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>test.dictionary.method_yn</code>.
     */
    public DictionaryRecord setMethodYn(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.method_yn</code>.
     */
    public Boolean getMethodYn() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>test.dictionary.view_yn</code>.
     */
    public DictionaryRecord setViewYn(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.view_yn</code>.
     */
    public Boolean getViewYn() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>test.dictionary.reg_dttm</code>. 등록 일시
     */
    public DictionaryRecord setRegDttm(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.reg_dttm</code>. 등록 일시
     */
    public LocalDateTime getRegDttm() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>test.dictionary.mod_dttm</code>. 수정 일시
     */
    public DictionaryRecord setModDttm(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>test.dictionary.mod_dttm</code>. 수정 일시
     */
    public LocalDateTime getModDttm() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Dictionary.DICTIONARY.TEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Dictionary.DICTIONARY.KOREAN_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Dictionary.DICTIONARY.ENGLISH_FULL_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Dictionary.DICTIONARY.ENGLISH_SHORT_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Dictionary.DICTIONARY.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Dictionary.DICTIONARY.PACKAGE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Dictionary.DICTIONARY.CLASS_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Dictionary.DICTIONARY.VARIABLE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return Dictionary.DICTIONARY.METHOD_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Dictionary.DICTIONARY.VIEW_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return Dictionary.DICTIONARY.REG_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return Dictionary.DICTIONARY.MOD_DTTM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getKoreanWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEnglishFullWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEnglishShortWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getPackageYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getClassYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getVariableYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getMethodYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getViewYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getRegDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getModDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKoreanWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEnglishFullWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEnglishShortWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getPackageYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getClassYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getVariableYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getMethodYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getViewYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getRegDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getModDttm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value1(Integer value) {
        setTestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value2(String value) {
        setKoreanWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value3(String value) {
        setEnglishFullWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value4(String value) {
        setEnglishShortWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value5(Boolean value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value6(Boolean value) {
        setPackageYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value7(Boolean value) {
        setClassYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value8(Boolean value) {
        setVariableYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value9(Boolean value) {
        setMethodYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value10(Boolean value) {
        setViewYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value11(LocalDateTime value) {
        setRegDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord value12(LocalDateTime value) {
        setModDttm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictionaryRecord values(Integer value1, String value2, String value3, String value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8, Boolean value9, Boolean value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictionaryRecord
     */
    public DictionaryRecord() {
        super(Dictionary.DICTIONARY);
    }

    /**
     * Create a detached, initialised DictionaryRecord
     */
    public DictionaryRecord(Integer testId, String koreanWord, String englishFullWord, String englishShortWord, Boolean useYn, Boolean packageYn, Boolean classYn, Boolean variableYn, Boolean methodYn, Boolean viewYn, LocalDateTime regDttm, LocalDateTime modDttm) {
        super(Dictionary.DICTIONARY);

        set(0, testId);
        set(1, koreanWord);
        set(2, englishFullWord);
        set(3, englishShortWord);
        set(4, useYn);
        set(5, packageYn);
        set(6, classYn);
        set(7, variableYn);
        set(8, methodYn);
        set(9, viewYn);
        set(10, regDttm);
        set(11, modDttm);
    }
}
