/*
 * This file is generated by jOOQ.
 */
package lee.minjae.testjooq.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dictionary implements Serializable {

    private static final long serialVersionUID = -1058241054;

    private final Integer       testId;
    private final String        koreanWord;
    private final String        englishFullWord;
    private final String        englishShortWord;
    private final Boolean       useYn;
    private final Boolean       packageYn;
    private final Boolean       classYn;
    private final Boolean       variableYn;
    private final Boolean       methodYn;
    private final Boolean       viewYn;
    private final LocalDateTime regDttm;
    private final LocalDateTime modDttm;

    public Dictionary(Dictionary value) {
        this.testId = value.testId;
        this.koreanWord = value.koreanWord;
        this.englishFullWord = value.englishFullWord;
        this.englishShortWord = value.englishShortWord;
        this.useYn = value.useYn;
        this.packageYn = value.packageYn;
        this.classYn = value.classYn;
        this.variableYn = value.variableYn;
        this.methodYn = value.methodYn;
        this.viewYn = value.viewYn;
        this.regDttm = value.regDttm;
        this.modDttm = value.modDttm;
    }

    public Dictionary(
        Integer       testId,
        String        koreanWord,
        String        englishFullWord,
        String        englishShortWord,
        Boolean       useYn,
        Boolean       packageYn,
        Boolean       classYn,
        Boolean       variableYn,
        Boolean       methodYn,
        Boolean       viewYn,
        LocalDateTime regDttm,
        LocalDateTime modDttm
    ) {
        this.testId = testId;
        this.koreanWord = koreanWord;
        this.englishFullWord = englishFullWord;
        this.englishShortWord = englishShortWord;
        this.useYn = useYn;
        this.packageYn = packageYn;
        this.classYn = classYn;
        this.variableYn = variableYn;
        this.methodYn = methodYn;
        this.viewYn = viewYn;
        this.regDttm = regDttm;
        this.modDttm = modDttm;
    }

    public Integer getTestId() {
        return this.testId;
    }

    public String getKoreanWord() {
        return this.koreanWord;
    }

    public String getEnglishFullWord() {
        return this.englishFullWord;
    }

    public String getEnglishShortWord() {
        return this.englishShortWord;
    }

    public Boolean getUseYn() {
        return this.useYn;
    }

    public Boolean getPackageYn() {
        return this.packageYn;
    }

    public Boolean getClassYn() {
        return this.classYn;
    }

    public Boolean getVariableYn() {
        return this.variableYn;
    }

    public Boolean getMethodYn() {
        return this.methodYn;
    }

    public Boolean getViewYn() {
        return this.viewYn;
    }

    public LocalDateTime getRegDttm() {
        return this.regDttm;
    }

    public LocalDateTime getModDttm() {
        return this.modDttm;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dictionary (");

        sb.append(testId);
        sb.append(", ").append(koreanWord);
        sb.append(", ").append(englishFullWord);
        sb.append(", ").append(englishShortWord);
        sb.append(", ").append(useYn);
        sb.append(", ").append(packageYn);
        sb.append(", ").append(classYn);
        sb.append(", ").append(variableYn);
        sb.append(", ").append(methodYn);
        sb.append(", ").append(viewYn);
        sb.append(", ").append(regDttm);
        sb.append(", ").append(modDttm);

        sb.append(")");
        return sb.toString();
    }
}
