/*
 * This file is generated by jOOQ.
 */
package lee.minjae.testjooq.jooq;


import javax.annotation.Generated;

import lee.minjae.testjooq.jooq.tables.Dictionary;
import lee.minjae.testjooq.jooq.tables.records.DictionaryRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DictionaryRecord, Integer> IDENTITY_DICTIONARY = Identities0.IDENTITY_DICTIONARY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DictionaryRecord> TEST_PK = UniqueKeys0.TEST_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DictionaryRecord, Integer> IDENTITY_DICTIONARY = Internal.createIdentity(Dictionary.DICTIONARY, Dictionary.DICTIONARY.TEST_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DictionaryRecord> TEST_PK = Internal.createUniqueKey(Dictionary.DICTIONARY, "test_pk", Dictionary.DICTIONARY.TEST_ID);
    }
}
