/*
 * This file is generated by jOOQ.
 */
package lee.minjae.testjooq.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>test.test_test_id_seq</code>
     */
    public static final Sequence<Integer> TEST_TEST_ID_SEQ = new SequenceImpl<Integer>("test_test_id_seq", Test.TEST, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
