/*
 * This file is generated by jOOQ.
 */
package lee.minjae.testjooq.jooq;


import javax.annotation.Generated;

import lee.minjae.testjooq.jooq.tables.Dictionary;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.dictionary</code>.
     */
    public static final Dictionary DICTIONARY = Dictionary.DICTIONARY;
}
